name: Testing with report download
run-name: Testing with downloading report process
on:
  push
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          architecture: x64

      - name: Build with Maven
        run: mvn -B clean package

      - name: Run Tests
        run: mvn test

      - name: Save Test Results
        run: mvn surefire-report:report-only

      - name: Testing time
        id: test
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: "YYYY_MM_DD HH_mm_ss"

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: tests/${{steps.test.outputs.date}}-${{steps.test.outputs.time}}-test-results-by-${{github.actor}}.txt

  download-report:
    runs-on: windows-latest
    needs: test
    name: Download report
    steps:
      - name: Download report file
        uses: actions/download-artifact@v4
        with:
          name: test-results